name: Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: Linux, python: '3.11', os: ubuntu-latest, nox: "tests"}
          - {name: Windows, python: '3.11', os: windows-latest, nox: "tests"}
          - {name: Mac, python: '3.11', os: macos-latest, nox: "tests"}
          - {name: Py313, python: '3.13', os: ubuntu-latest, nox: "tests"}
          - {name: Py312, python: '3.12', os: ubuntu-latest, nox: "tests"}
          - {name: Py310, python: '3.10', os: ubuntu-latest, nox: "tests"}
          - {name: Lint, python: '3.11', os: ubuntu-latest, nox: "lint"}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install uv
        run: pip install uv
      - name: Sync
        run: make sync
      - name: Run tests
        run: make test
